### ISSUE TITLE
Update XFC range to 1MW+ to reflect industry announcements

### ISSUE THREAD

**Issue by HVCSFriend** [nmfta-repo/nmfta-hvcs-xfc#1]
Please update the upper charging limits in the technical report to "1MW+" to reflect varying upper limit targets by different HD truck OEMs. There are three instances highlighted in the attached. 

https://electrek.co/2019/07/10/tesla-high-power-charging-standard-electric-trucks/

[XFC Cybersecurity Requirements For Medium and Heavy Duty Electric Vehicles  07.15.2019.pdf](https://github.com/nmfta-repo/nmfta-hvcs-xfc/files/3392875/XFC.Cybersecurity.Requirements.For.Medium.and.Heavy.Duty.Electric.Vehicles.07.15.2019.pdf)

**Comment by HVCSFriend** [comment]
Fixed issue with NMFTA logo

[NMFTA HVCS XFC 07-19-19 V4 Cybersecurity Requirements - Final.pdf](https://github.com/nmfta-repo/nmfta-hvcs-xfc/files/3427498/NMFTA.HVCS.XFC.07-19-19.V4.Cybersecurity.Requirements.-.Final.pdf)

**Comment by BenGardiner** [comment]
> Fixed issue with NMFTA logo
> 
> [NMFTA HVCS XFC 07-19-19 V4 Cybersecurity Requirements - Final.pdf](https://github.com/nmfta-repo/nmfta-hvcs-xfc/files/3427498/NMFTA.HVCS.XFC.07-19-19.V4.Cybersecurity.Requirements.-.Final.pdf)

Does this PDF also resolve the changes requested in issue #2 ?

**Comment by HVCSFriend** [comment]
Yes. I removed a shadow line from the outline of the logo.

 

Alison Hwang 

Analyst/Program Coordinator HVCS
National Motor Freight Traffic Association, Inc. 
1001 N. Fairfax St., Suite 600 
Alexandria, VA 22314   

E-mail: Alison.Hwang@nmfta.org 
Phone: +1 (703) 838-8838
Fax: +1 (703) 683-6296 
 <http://www.nmfta.org/> www.nmfta.org
